"""initial schema

Revision ID: c76e4804ff63
Revises: 
Create Date: 2026-06-29 20:46:48.996725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76e4804ff63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('inspections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('conf', sa.Float(), nullable=False),
    sa.Column('imgsz', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('n_images', sa.Integer(), nullable=False),
    sa.Column('n_defects', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_user_id'), ['user_id'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('inspection_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('annotated_path', sa.String(length=500), nullable=False),
    sa.Column('cam_path', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('n_defects', sa.Integer(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('inspection_id', sa.String(length=32), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('used_llm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('detections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('inspection_id', sa.String(length=32), nullable=False),
    sa.Column('cls_name', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_cls_name'), ['cls_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_inspection_id'), ['inspection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_detections_image_id'))
        batch_op.drop_index(batch_op.f('ix_detections_cls_name'))

    op.drop_table('detections')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_inspection_id'))

    op.drop_table('reports')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_inspection_id'))

    op.drop_table('images')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_user_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_created_at'))

    op.drop_table('inspections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
